"""add_document_checks_and_api_keys

Revision ID: 30a7deb628a2
Revises: e62b8ed9ee46
Create Date: 2026-06-20 17:34:16.673172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a7deb628a2'
down_revision: Union[str, None] = 'e62b8ed9ee46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
